# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vote_app(object):
    def setupUi(self, vote_app):
        vote_app.setObjectName("vote_app")
        vote_app.resize(500, 400)
        vote_app.setMinimumSize(QtCore.QSize(500, 400))
        vote_app.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(parent=vote_app)
        self.centralwidget.setObjectName("centralwidget")
        self.label_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(-10, 0, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setUnderline(False)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.name_text_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_text_box.setGeometry(QtCore.QRect(170, 130, 181, 20))
        self.name_text_box.setObjectName("name_text_box")
        self.label_info = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_info.setGeometry(QtCore.QRect(140, 60, 221, 61))
        self.label_info.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.label_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(110, 130, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_name.setFont(font)
        self.label_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.email_text_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.email_text_box.setGeometry(QtCore.QRect(170, 170, 181, 20))
        self.email_text_box.setObjectName("email_text_box")
        self.label_email = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(110, 170, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_email.setFont(font)
        self.label_email.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_email.setObjectName("label_email")
        self.phone_text_box = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.phone_text_box.setGeometry(QtCore.QRect(170, 210, 181, 20))
        self.phone_text_box.setText("")
        self.phone_text_box.setObjectName("phone_text_box")
        self.label_phone = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_phone.setGeometry(QtCore.QRect(110, 210, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_phone.setFont(font)
        self.label_phone.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_phone.setObjectName("label_phone")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(270, 250, 81, 31))
        self.submit_button.setObjectName("submit_button")
        self.reset_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(170, 250, 81, 31))
        self.reset_button.setObjectName("reset_button")
        self.exit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(390, 340, 61, 21))
        self.exit_button.setObjectName("exit_button")
        vote_app.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=vote_app)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        vote_app.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=vote_app)
        self.statusbar.setObjectName("statusbar")
        vote_app.setStatusBar(self.statusbar)

        self.retranslateUi(vote_app)
        QtCore.QMetaObject.connectSlotsByName(vote_app)

    def retranslateUi(self, vote_app):
        _translate = QtCore.QCoreApplication.translate
        vote_app.setWindowTitle(_translate("vote_app", "Voting Application"))
        self.label_title.setText(_translate("vote_app", "Welcome to the vote application!"))
        self.label_info.setText(_translate("vote_app", "Please enter: Name, Email and Phone number"))
        self.label_name.setText(_translate("vote_app", "Name"))
        self.label_email.setText(_translate("vote_app", "Email"))
        self.label_phone.setText(_translate("vote_app", "Phone"))
        self.submit_button.setText(_translate("vote_app", "SUBMIT"))
        self.reset_button.setText(_translate("vote_app", "RESET"))
        self.exit_button.setText(_translate("vote_app", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vote_app = QtWidgets.QMainWindow()
    ui = Ui_vote_app()
    ui.setupUi(vote_app)
    vote_app.show()
    sys.exit(app.exec())
