# Form implementation generated from reading ui file 'second_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_second_screen(object):
    def setupUi(self, second_screen):
        second_screen.setObjectName("second_screen")
        second_screen.resize(500, 400)
        second_screen.setMinimumSize(QtCore.QSize(500, 400))
        second_screen.setMaximumSize(QtCore.QSize(500, 400))
        self.centralwidget = QtWidgets.QWidget(parent=second_screen)
        self.centralwidget.setObjectName("centralwidget")
        self.radio_john = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_john.setGeometry(QtCore.QRect(210, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radio_john.setFont(font)
        self.radio_john.setChecked(True)
        self.radio_john.setObjectName("radio_john")
        self.label_title2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_title2.setGeometry(QtCore.QRect(-10, 0, 521, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setUnderline(False)
        self.label_title2.setFont(font)
        self.label_title2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title2.setObjectName("label_title2")
        self.label_info2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_info2.setGeometry(QtCore.QRect(0, 60, 501, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_info2.setFont(font)
        self.label_info2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_info2.setObjectName("label_info2")
        self.radio_jane = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_jane.setGeometry(QtCore.QRect(210, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radio_jane.setFont(font)
        self.radio_jane.setObjectName("radio_jane")
        self.vote_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_button.setGeometry(QtCore.QRect(200, 190, 81, 41))
        self.vote_button.setObjectName("vote_button")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 340, 75, 23))
        self.pushButton.setObjectName("pushButton")
        second_screen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=second_screen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 21))
        self.menubar.setObjectName("menubar")
        second_screen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=second_screen)
        self.statusbar.setObjectName("statusbar")
        second_screen.setStatusBar(self.statusbar)

        self.retranslateUi(second_screen)
        QtCore.QMetaObject.connectSlotsByName(second_screen)

    def retranslateUi(self, second_screen):
        _translate = QtCore.QCoreApplication.translate
        second_screen.setWindowTitle(_translate("second_screen", "Voting Application"))
        self.radio_john.setText(_translate("second_screen", "John"))
        self.label_title2.setText(_translate("second_screen", "Who will you vote for?"))
        self.label_info2.setText(_translate("second_screen", "Welcome {name} please select a candidate!"))
        self.radio_jane.setText(_translate("second_screen", "Jane"))
        self.vote_button.setText(_translate("second_screen", "VOTE"))
        self.pushButton.setText(_translate("second_screen", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    second_screen = QtWidgets.QMainWindow()
    ui = Ui_second_screen()
    ui.setupUi(second_screen)
    second_screen.show()
    sys.exit(app.exec())
